which_gpu : 1
no_replicates : 5
test_size : 500
model:
  no_features : 6
  hidden_sizes : 
    - 64
    - 64
    - 32
  dropout_rate : 0.1
  feature_dropout : 0.05
  use_exu : False
training:
  regression : False
  batch_size : 16
  max_epochs : 10
  verbosity : 20
  learning_rate : 2.e-4
  weight_decay : 0.
  output_penalty : .2
plotting:
  roc:
    size:
      - 5
      - 3
    fname : './results/roc.png'
  shapes:
    nrows : 3
    size:
      - 10
      - 10
    fname : './results/shapes.png'
